server:
  port: 8500
  servlet:
    encoding:
      force-response: true
    #配置项目访问路径
    context-path: /mybatis-plus-spring-native-demo

spring:
  datasource:
    url: jdbc:mysql://192.168.230.1:3306/mybatis-demo?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: su@su123456.
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.withmes: debug
